lessons/urls.py
from django.contrib import admin
from django.urls import path
from lessons import views

app_name = "lessons"

urlpatterns = [
    path('',views.lessons, name ="lessons"),
    path('lesson/<int:id>',views.detail, name ="detail"),
    path('addlesson/',views.addLesson, name ="addlesson")
]

student/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from user import views
from dashboard import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name= "index"),
    path("user/",include('user.urls')),
    path("lessons/",include('lessons.urls'))
]

user/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("register/",views.register,name = 'register'),
    path("login/",views.loginUser,name = 'login'),
    path("logout/",views.logoutUser,name = 'logout'),

]

dashboard/models.py
from django.db import models

# Create your models here.

lessons/models.py
from django.db import models

# Create your models here.

class Lesson(models.Model):
       # djangonun icindeki hazir olan authentication tablosundan bir tane
    # foreignKey aliyoruz
    # cunku her bir dersi bir kullaniciya ait olmali
   
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE)
    lesson_name = models.CharField(max_length = 50 ,verbose_name ="Ders Adi")
    content = models.CharField(max_length = 250 ,verbose_name ="Ders Aciklamasi",null=True)
    # bu bize o anki tarihi atar.Veri eklendiginde
    created_date = models.DateTimeField(auto_now_add=True)

    # def str bize admin panelinde lesson_name bilgisini ozellestirerek gosteriyor
    def __str_(self):
        return self.author
    
    #modelimizde en son eklenen en ustte gosterildi
    class Meta:
        ordering = ['-created_date']


class Attendance(models.Model):
    
    lesson = models.ForeignKey(Lesson,on_delete = models.CASCADE,verbose_name ="Ders Adi")
    attendance_date = models.DateTimeField(verbose_name ="Yoklama Tarihi")
    created_date = models.DateTimeField(auto_now_add = True)

    def __str_(self):
        return self.lesson

    class Meta:
        ordering = ['-created_date']

user/models.py
from django.db import models

# Create your models here.

lessons/forms.py
from django import forms
from .models import Lesson,Attendance


class LessonForm(forms.ModelForm):

    class Meta:
        model = Lesson

        # formda goruntulenecek alanlar
        fields = ["lesson_name","content"]

class AttendanceForm(forms.ModelForm):

    class Meta:
        model = Attendance

        # formda goruntulenecek alanlar
        fields = ["lesson","attendance_date"]

user/forms.py
from django import forms
from django.forms.widgets import PasswordInput, Widget


class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanici Adi")
    password = forms.CharField(label ="Parola" ,widget = forms.PasswordInput)


class RegisterForm(forms.Form):

    username = forms.CharField(max_length=50,label="Kullanici Adi")
    password = forms.CharField(max_length= 20 ,label="Parola" ,widget= forms.PasswordInput)
    confirm = forms.CharField(max_length = 20 , label = "Parolayi dogrula",widget= forms.PasswordInput)
    #sifrelerin ayni olup olmadigi kontrolu clean
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar eslesmiyor")
        
        values ={
            "username" : username,
            "password" : password,
            
        }
        return values

dashboard/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {
        "numbers": [1, 2, 3, 4, 5, 6]
    }
    return render(request, "index.html", context)

lessons/views.py
from django.shortcuts import render,redirect ,get_object_or_404

from lessons.forms import LessonForm, AttendanceForm
from django.contrib import messages

from .models import Lesson
# Create your views here.


def addLesson(request):
    # Form Kayit
    # request.POST bizim yazi alanlarimizi yukler

    form = LessonForm(request.POST or None)

    if form.is_valid():

        lesson = form.save(commit=False)
        # Hangi Kullanici Giris yapmissa
        lesson.author = request.user

        lesson.save()
        messages.success(request,"Basariyla Ders Olusturuldu")
        return redirect("index")
    return render(request,"addlesson.html",{"form":form})

def lessons(request):
        
    keyword = request.GET.get("keyword")
    if keyword:
            lessons = Lesson.objects.filter(title__contains=keyword)
            # sadece aramalarda cikan article lar gelecek
            return render(request, "lessons.html", {"lessons": lessons})

    
    lessons = Lesson.objects.all()
    return render(request, "lessons.html", {"lessons": lessons})


def detail(request, id):
    # lesson = Lesson.objects.filter(id = id ).first()#ilk elemani aldik filter liste halinde getiriyor
    # id var ise getir yoksa 404 getir
    lesson = get_object_or_404(Lesson, id=id)

    # Comment yorum alani related_name = comments ile erisiyoruz
    # comments = lesson.comments.all()

    form = AttendanceForm(request.POST or None)

    if form.is_valid():

        attendance = form.save(commit=False)
        # Hangi Kullanici Giris yapmissa
        attendance.author = request.user

        attendance.save()
        messages.success(request,"Yoklama Olusturuldu")
        
    return render(request, "detail.html", {"lesson": lesson,"form_attendance":form})

user/views.py
from django.shortcuts import render ,redirect
#redirect index sayfasina yonlendirmek icin kullandik

from . forms import RegisterForm ,LoginForm


#user modelini dahil ettik hazir django da bulunuyor
from django.contrib.auth.models import User

#login icin
#logout icin 
from django.contrib.auth import authenticate, login ,logout
#authenticate bize veri tabaninda kullanici olup olmadigini kontrol eder

#mesajlar icin 
from django.contrib import messages
# Create your views here.











def register(request):

    #post veya get request olsada kontrollu bir sekilde biliyoruz
    form = RegisterForm(request.POST or None)

    #requestimiz get ise bos gelecegi icin hic if bloguna girmez render ile context gonderilir
    if form.is_valid(): #form.is_valid() yaptigimizda clean methodu cagirilir ve eger true gelirse bu blog calisir
        #values teki degerler
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        #kullanici veriTabanina kayit etme islemi
        newUser = User(username = username)
        newUser.set_password(password) #parola sifreli olarak gonderildi

        newUser.save() #kayit edildi
        #kayit ettikten sonra sisteme giris yapmasini belirliyoruz
        login(request,newUser) #login edildi
       
        messages.success(request,"Basariyla Kayit Oldunuz")


        #ana sayfaya yonlendirmek icin
        return redirect("index")

    #post gelse bile kayit basariyla gerceklezse ayni sayfayi tekrar render ettik 
    context = {
            "form": form #contexte form bilgimizi verdik
        }
    return render(request,"accounts/register.html",context)




def loginUser(request):

    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username =form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        
        #veri tabani kontrolu authenticate metodu 
        user = authenticate(username =  username,password = password)
        
        #veri tabani ile eslesmiyorsa if e girer 
        if user is None:
            messages.info(request,"Kullanici adi Veya parolaniz yanlis !!")
            return render(request,"login.html",context)

        #giris basariliysa
        messages.success(request,"Basariyla giris yaptiniz")
        login(request,user)
        return redirect("index")
    return render(request,"accounts/login.html",context)



def logoutUser(request):
    logout(request)
    messages.success(request,"Basariyla Cikis Yapildi")
    return redirect("index")

templates/accounts/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block body %} 
<br><br><br>
<div class="container ">
<div class="row ">
  <div class="col-md-6 offset-md-3 bg-light shadow">
    <h3 class="text-center">Giris Yap</h3>
    <hr class= "bg-danger">

    <form action="" method = "post" class="">
        {% comment %} ma n in the midle gibi ataklardan korunmak icin csrf_token {% endcomment %}
         {% csrf_token %} 
        {{form | crispy }}
        <br>
        <button type = "submit" class = "btn btn-outline-danger w-100 ">Giris Yap</button>
       
    </form>
    <hr class= "bg-dark">
    <button type = "submit" class = "btn btn-danger w-100 ">Kayit Ol</button>
     </div>
    </div>
</div>
{% endblock body %}

templates/accounts/register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block body %} 
<br><br><br>
<div class="container ">
<div class="row ">
  <div class="col-md-6 offset-md-3 bg-light shadow">
    <h3 class="text-center">Kayit ol</h3>
    <hr class= "bg-danger">

    <form action="" method = "post" class="">
        {% comment %} ma n in the midle gibi ataklardan korunmak icin csrf_token {% endcomment %}
         {% csrf_token %} 
        {{form | crispy }}
        <br>
        <button type = "submit" class = "btn btn-outline-danger w-100 ">Kayit Ol</button>
       
    </form>
    <hr class= "bg-dark">
    <button type = "submit" class = "btn btn-danger w-100 ">Giris Yap</button>
     </div>
    </div>
</div>
{% endblock body %}

templates/addlesson.html
{% extends "base.html" %}

{% block body %}
{% load crispy_forms_tags %}


<div class="row">
  <div class="col-md-6 offset-md-3">

    <h3>Ders Olustur</h3>
    <hr>

    <form method = "post" enctype="multipart/form-data">
    {% csrf_token %}

    
    {{form | crispy}}
    
    <button type ="submit" class = "btn btn-danger">Olustur</button>
    </form>

 </div>
    </div>

{% endblock body %}

templates/base-full-screen.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ogrenci Katilim</title>


 <!-- Bootstrap icin css eklendi static dosyamizin icinde-->
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}"> {% endcomment %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


</head>
<body>

<div class="container">
    

        
    
    
        {% include "includes/navbar.html" %}
      
        
       
    
        {% block body %} 

        {% endblock body %}

        

</div>


        <!-- Bootstrap icin JavaScript eklendi -->
    {% comment %} <script src = "{% static 'js/bootstrap.min.js'%}"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
 
</body>
</html>

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ogrenci Katilim</title>


 <!-- Bootstrap icin css eklendi static dosyamizin icinde-->
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}"> {% endcomment %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <!--  DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />

</head>
<body class="bg-light">


          {% include "includes/navbar-base.html" %}

     <div style="margin-top :100px;" class="container">
          {% csrf_token %}
           {% if messages %}
            {% for message in messages %}
                {% if message.tags == "info" %}
                     <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <input id="datetimepicker" type="text">

        <script>
          $(function () {
            $("#datetimepicker").datetimepicker();
          });
        </script>

        {% block body %} 

   
        {% endblock body %}
   
        

</div>









        <!-- Bootstrap icin JavaScript eklendi -->
    {% comment %} <script src = "{% static 'js/bootstrap.min.js'%}"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

</body>
</html>

templates/detail.html
{% extends "base.html" %}


{% block body %}

{% load crispy_forms_tags %}


  <div class="container shadow">
    <div class="row">
      <div class="col">
        <ol class="list-group list-group-numbered">
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <div class="fw-bold">Subheading</div>
              Cras justo odio
            </div>
            <span class="badge bg-primary rounded-pill">14</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <div class="fw-bold">Subheading</div>
              Cras justo odio
            </div>
            <span class="badge bg-primary rounded-pill">14</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <div class="fw-bold">Subheading</div>
              Cras justo odio
            </div>
            <span class="badge bg-primary rounded-pill">14</span>
          </li>
        </ol>
      </div>
      <div class="col-7">

        <button class="btn btn-warning" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBackdrop" aria-controls="offcanvasWithBackdrop">Yoklama Aktif Et</button>

        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5">
              <h3 class=" fs-5">{{ lesson.lesson_name }}</h3>
              
              <p class="col-md-8 fs-7">{{ lesson.content }}</p>
              <button class="btn btn-primary btn-lg" type="button">Example button</button>
            </div>
          </div>
        
        
        
        
      </div>
      <div class="col">
        <ol class="list-group list-group-numbered">
            <li class="list-group-item d-flex justify-content-between align-items-start">
              <div class="ms-2 me-auto">
                <div class="fw-bold">Subheading</div>
                Cras justo odio
              </div>
              <span class="badge bg-primary rounded-pill">14</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start">
              <div class="ms-2 me-auto">
                <div class="fw-bold">Subheading</div>
                Cras justo odio
              </div>
              <span class="badge bg-primary rounded-pill">14</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start">
              <div class="ms-2 me-auto">
                <div class="fw-bold">Subheading</div>
                Cras justo odio
              </div>
              <span class="badge bg-primary rounded-pill">14</span>
            </li>
          </ol>
      </div>
    </div>
    
  </div>








  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasWithBackdrop" aria-labelledby="offcanvasWithBackdropLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasWithBackdropLabel">Offcanvas with backdrop</h5>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
     


      <div class="row">
        <div class="col-md-6 offset-md-3">
      
          <h3>Ders Olustur</h3>
          <hr>
      
          <form method = "post" enctype="multipart/form-data">
          {% csrf_token %}
      
         
          {{form_attendance | crispy}}
          
          <button type ="submit" class = "btn btn-danger">Olustur</button>
          </form>
      
       </div>
          </div>
          <input id="datetimepicker" type="text">

        
          <script>
            $(function () {
              $("#datetimepicker").datetimepicker();
            });
          </script>

    </div>
  </div>

{% endblock body %}


</script>

templates/includes/navbar-base.html
{% load static %}


    <header class="%100 % bg-light shadow d-flex flex-wrap align-items-center justify-content-center py-3 mb-4 border-bottom">
      <a href="{% url 'index'%}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <img width="50" height="50"src={%  static 'images/iste_arma.png' %} alt="">
      </a>

      <ul class="nav nav-tabs col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li class="nav-item  "><a href="{% url 'index' %}" class="nav-link   {% if '/' == request.path %}  active link-secondary   {% endif %}">Ana Sayfa</a></li>
        <li><a href="{% url 'lessons:lessons' %}" class="nav-link px-2 {% if 'lessons' in request.path %}  active link-secondary  {% endif %} ">Dersler</a></li>
        <li><a href="#" class="nav-link px-2 {% if '/' == request.path %} link-secondary   {% endif %}">Hakkimizda</a></li>
        <li><a href="#" class="nav-link px-2 {% if '/' == request.path %} link-secondary   {% endif %}">Iletisim</a></li>
        <li><a href="#" class="nav-link px-2 {% if '/' == request.path %} link-secondary   {% endif %}">About</a></li>

 <!-- Kullanicinin Giris Yapilip Yapilmadigina gore navbarda Giris veya Cikis Butonu Gosteriyoruz -->
  {% if request.user.is_authenticated %}<!-- kullanici giris yapmissa bu bloga girer -->
        <li class="nav-item active">

                <a class="btn btn-success" href="">{{request.user.username}}</a>
            </li>
             <li class="nav-item active">
          <a class="nav-link" href="">Kontrol Paneli</a>
         </li>

          </ul>
  <a href="{% url 'user:logout'%}">
              <button type="button" class="btn btn-outline-danger me-2">Logout</button>

      </a>
   
  
  {% else %}
<div class=" text-end">
      <a href="{% url 'user:login'%}">
              <button type="button" class="btn btn-outline-danger me-2">Login</button>

      </a>
        <a href="{% url 'user:register'%}">
             <button type="button" class="btn btn-danger">Sign-up</button>
      </a>
      </div>

  {% endif %}
      
    </header>

templates/includes/navbar.html
      <header class="navbar navbar-dark sticky-top bg-light flex-md-nowrap p-0 shadow"> 
 <a class="navbar-brand bg-success  col-md-1 col-lg-2 me-0 px-3" href="#">Ahmet Ozkan</a> 

    
     
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-dark">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">About</a></li>
        </ul>



        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-success" placeholder="Search..." aria-label="Search">
        </form>



        <div class="text-end">
          <button type="button" class="btn btn-outline-dark me-2">Login</button>
          <button type="button" class="btn btn-outline-success">Sign-up</button>
        </div>
      </div>
    </div>
 
  






{% comment %} 
  <div class="navbar-nav bg-dark ">
    <div class="nav-item  text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
    
  </div>  {% endcomment %}



  
<div class="container-fluid ">
  <div class="row">
    <nav style="bagroundcolor:" id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse shadow">
      <div class="position-sticky pt-1">
        <ul class="nav flex-column">
          <li class="nav-item hover-outline">
           
            <a class="nav-link text-dark" aria-current="page" href="#">

              <span data-feather="home"></span>
               Dashboard

          
            </a>
         
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link text-dark" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
    
        </ul>
      </div>
    </nav>
        </div>
            </div>

 </header>    

templates/index.html
{% extends "base.html" %}


{% block body %}


<br>
<main class="px-3 text-center">
    <h1>Merhaba Ahmet Ozkan Bloguna Hosgeldiniz.</h1>
    <p class="lead">Bu blog Django ile yazilmistir.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>

{% if request.user.is_authenticated %}
    Giris Yapilmis, {{request.user.username}}
{%else %}
    Giris yapilmamis
{% endif %}





{% endblock body %}

templates/lessons.html
{% extends "base.html" %}


{% block body %}




    {% if lessons %}


    <div class="container ">
      <div class="row">
    {% for lesson in lessons %}
        
    
    <div class="col-6 col-md-4 ">

      <div class="card shadow" style="width: 18rem;">
       
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{lesson.lesson_name}}</h5>
          <p class="card-text">{{lesson.content}}</p>
          <a href="{% url 'lessons:detail' lesson.id %}" class="btn btn-outline-primary">Ders Icerigi</a>
          <a href="{% url 'user:login' %}" class="btn btn-primary position-relative">Yoklama Al
          
            <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
              <span class="visually-hidden">New alerts</span>
            </span>
          </a>  
        </div>
      </div>

    </div>
    
   
    
    {% endfor %}
    
  </div>
</div>
    {% else %}
    <h1>Herhangi kayitli bir ders bulunmuyor</h1>
    {% endif %}
 

{% endblock body %}

templates/widgets/datetimepicker.html
{% include "base.html" %}

<script>
  $(function () {
    $("input[name='{{ widget.name }}']").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
</script>